openapi: "3.1.0"

info:
  title: "ecommerce REST API"
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.0

servers:
  - url: "http://localhost:4000"

paths:
  /products:
    get:
      summary: Returns a list of products.
      description: Returns a list of products.
      tags:
        - products_endpoint
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: string
                    description:
                      type: string
  /products/{productId}:
    get:
      summary: Returns a product by ID.
      description: Returns a product by ID.
      tags:
        - products_endpoint
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        "200": # status code
          description: A JSON product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: string
                  description:
                    type: string
  /auth/register:
    post:
      summary: Register a user.
      description: Register a user.
      tags:
        - authentication_endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                password:
                  type: string
      responses:
        "201": # status code
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  password:
                    type: string
                  updatedTime:
                    type: string
  /auth/login:
    post:
      summary: Login a user.
      description: Login a user.
      tags:
        - authentication_endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
  /users/{userId}:
    get:
      summary: Get a user data by ID.
      description: Get a user data by ID.
      tags:
        - user_endpoint
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user data to get
      responses:
        "200": # status code
          description: A JSON user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  password:
                    type: string
                  updatedTime:
                    type: string
    put:
      summary: Update a user data by ID.
      description: Update a user data by ID.
      tags:
        - user_endpoint
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user data to updatedTime
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                password:
                  type: string
      responses:
        "200": # status code
          description: A JSON user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  password:
                    type: string
                  updatedTime:
                    type: string
