openapi: "3.1.0"

info:
  description: "ecommerce REST API"
  version: "0.0.0"
  title: "ecommerce REST API"

host: localhost:4000

paths:
  /products:
    get:
      summary: Returns a list of products.
      description: Returns a list of products.
      tags:
        - products_endpoint
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: string
                    description:
                      type: string
  /products/{productId}:
    get:
      summary: Returns a product by ID.
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      description: Returns a product by ID.
      tags:
        - products_endpoint
      responses:
        "200": # status code
          description: A JSON product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: string
                  description:
                    type: string
